name: Build node_modules
on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip project
        run: unzip -o dailyco-mobile.zip -d .
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm install --no-audit --no-fund
      - uses: actions/upload-artifact@v4
        with:
          name: node_modules
          path: node_modules
